export const serviceMembers = [
    {name: 'Service-1',       img: '/img/Services/service-1.jpg'},
    {name: 'Service-2',     img: '/img/Services/service-2.jpg'},
    {name: 'Service-3',      img: '/img/Services/service-3.jpg'},
    {name: 'Service-4',        img: '/img/Services/service-4.jpg'},
    {name: 'Service-5',      img: '/img/Services/service-5.jpg'},
    {name: 'Service-6',     img: '/img/Services/service-6.jpg'},
    {name: 'Service-7',      img: '/img/Services/service-7.jpg'},
    {name: 'Service-8',      img: '/img/Services/service-8.jpg'},
    {name: 'Service-9',      img: '/img/Services/service-9.jpg'},
    {name: 'Service-10',      img: '/img/Services/service-10.jpg'},
    {name: 'Service-11',      img: '/img/Services/service-11.jpg'},
    {name: 'Service-12',      img: '/img/Services/service-12.jpg'},
    {name: 'Service-13',      img: '/img/Services/service-13.jpg'},
    {name: 'Service-14',      img: '/img/Services/service-14.jpg'},
    {name: 'Service-15',      img: '/img/Services/service-15.jpg'},
    {name: 'Service-16',      img: '/img/Services/service-16.jpg'},
    {name: 'Service-17',      img: '/img/Services/service-17.jpg'},
    {name: 'Service-18',      img: '/img/Services/service-18.jpg'},
    {name: 'Service-19',      img: '/img/Services/service-19.jpg'},
    {name: 'Service-20',      img: '/img/Services/service-20.jpg'},

];
