export const staffMembers = [
    {name: 'Brad',       img: '/img/Services/service-1.jpg'},
    {name: 'Sherry',     img: '/img/Services/service-2.jpg'},
    {name: 'Laura',      img: '/img/Services/service-3.jpg'},
    {name: 'Jan',        img: '/img/Services/service-4.jpg'},
    {name: 'Susan',      img: '/img/Services/service-5.jpg'},
    {name: 'Claire',     img: '/img/Services/service-6.jpg'},
    {name: 'Steph',      img: '/img/Services/service-7.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-8.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-9.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-10.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-11.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-12.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-13.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-14.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-15.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-16.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-17.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-18.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-19.jpg'},
    {name: 'Tracy',      img: '/img/Services/service-20.jpg'},

];
